AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example lambdas instrumented using different handlers and wrappers

Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  # layer-based example
  RequestFunctionWithLayer:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: RequestFunctionWithLayer
      CodeUri: .
      Handler: com.splunk.support.lambda.TracingRequestWrapper::handleRequest
      Runtime: java11
      Timeout: 60
      MemorySize: 256
      Layers:
        - arn:aws:lambda:us-east-2:906383545488:layer:otel-lambda-java-wrapper:26
      Environment:
        Variables:
          OTEL_INSTRUMENTATION_AWS_LAMBDA_HANDLER: com.splunk.support.lambda.examples.RequestFunction::handleRequest
          OTEL_INSTRUMENTATION_AWS_LAMBDA_FLUSH_TIMEOUT: 30000
          OTEL_TRACES_EXPORTER: logging
          OTEL_LAMBDA_LOG_LEVEL: DEBUG
          OTEL_LIB_LOG_LEVEL: FINEST