include:
  - project: 'prodsec/scp-scanning/gitlab-checkmarx'
    ref: latest
    file: '/templates/.sast_scan.yml'
  - project: 'prodsec/whitesource'
    ref: latest
    file: '/templates/.whitesource.yml'

image:
  name: "maven:3-jdk-8"

stages:
  - verify
  - release

sast-scan:
  stage: verify
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
  extends: .sast_scan
  variables:
    SAST_SCANNER: "Semgrep"
    # Fail build on high severity security vulnerabilities
    alert_mode: "policy"

whitesource:
  stage: verify
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
  extends: .whitesource
  variables:
    ws_user_key: ${WHITESOURCE_USER_KEY}
    product_id: ${WHITESOURCE_ID}
    config: java-maven
    lib_path: "${CI_PROJECT_DIR}/wrapper"

release:
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG =~ /^rc[0-9]+\.[0-9]+\.[0-9]+.*/'
  script:
    - export VERSION=${CI_COMMIT_TAG:2} && echo "Release version used $VERSION"
    - export NEXT=$(perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e' <<< "$VERSION") && echo "Next development version $NEXT"
    - export DEBUG=true
    - export GH_REPO=signalfx/splunk-otel-java-lambda
    - .gitlab-ci/setup-tooling.sh
    - .gitlab-ci/setup-github.sh ${VERSION}
    - .gitlab-ci/pre-release.sh ${VERSION}
    - .gitlab-ci/release-binaries.sh ${VERSION}
    - .gitlab-ci/post-release.sh ${VERSION} ${NEXT}-SNAPSHOT